version: 0.2

env:
  shell:
    /bin/bash
  variables:
    EXEC_PATH: "target/release/data_processing"

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env

  build:
    commands:
      - cargo build --release

artifacts:
  files:
    - $EXEC_PATH
  discard-paths: yes

cache:
  paths:
  - $HOME/.cargo/registry/**/*
